config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "pages#home"

  resources :super_powers do
    resources :orders, only: %i[create new]
    resources :reviews, only: %i[create new]
  end
  resources :orders, except: %i[edit destroy]
  resources :reviews, only: :destroy

  get '/ads', to: 'super_powers#ads', as: 'ads'

  get '/shopping', to: 'orders#shopping', as: 'shopping'

  get 'users/:id', to: 'users#show', as: 'user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :owner, class_name: 'User'
  belongs_to :super_power
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :super_power
  validates :rating, inclusion: 0..5
  validates :comment, length: {minimum: 5}
  validates :rating, :comment, presence: true
end

app/models/super_power.rb
class SuperPower < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
                  against: %i[name description],
                  ignoring: :accents,
                  associated_against: {
                    user: [:name]
                  },
                  using: { tsearch: { prefix: true } }

  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_one_attached :photo
  validates :name, :description, :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
  has_many :super_powers
  has_many :user_orders, class_name: 'Order', foreign_key: 'user_id'
  has_many :owner_orders, class_name: 'Order', foreign_key: 'owner_id'
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: [:index, :ads, :shopping], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index, :ads, :shopping], unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)|(^users$)/
  end

  protected

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :img, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :img, :photo])
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: :show

  def new
    @order = Order.new
    @super_power = SuperPower.find(params[:super_power_id])
    @order.super_power_id = @super_power.id
    authorize @order
  end

  def create
    @order = Order.new
    @super_power = SuperPower.find(params[:super_power_id])
    @order.super_power_id = @super_power.id
    @order.user_id = current_user.id
    @order.owner_id = @super_power.user_id
    authorize @order
    if @order.save
      flash[:notice] = 'Congratulations, you have a new Super Power!'
      redirect_to order_path(@order)
    else
      render :new
    end
  end

  def show
    authorize @order
  end

  def shopping
    @orders = policy_scope(Order).where(user: current_user)
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @super_power = SuperPower.find(params[:super_power_id])
    @review.super_power = @super_power
    authorize @review
    if @review.save
      redirect_to super_power_path(@super_power)
    else
      redirect_to super_power_path(@super_power), status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/super_powers_controller.rb
class SuperPowersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_super_power, only: %i[show edit update]

  def index
    if params[:query].present?
      @super_powers = SuperPower.search_by_name_and_description(params[:query])
      skip_policy_scope
    else
      @super_powers = policy_scope(SuperPower)
    end
  end

  def show
    @review = Review.new
    @users = User.all
    @related = SuperPower.all.sample(3)
  end

  def ads
    @super_powers = policy_scope(SuperPower).where(user: current_user)
  end

  def new
    @super_power = SuperPower.new
    authorize @super_power
  end

  def create
    @super_power = SuperPower.new(super_power_params)
    @super_power.user_id = current_user.id
    authorize @super_power
    if @super_power.save
      redirect_to ads_path
    else
      render "new", status: :unprocessable_entity
    end
  end

  def destroy
    @super_power = SuperPower.find(params[:id])
    authorize @super_power
    if @super_power.destroy
      redirect_to ads_path, notice: 'Super Power destroyed'
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @super_power.update(super_power_params)
      redirect_to @super_power, notice: "Super Power was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def super_power_params
    params.require(:super_power).permit(:name, :description, :price, :img, :photo)
  end

  def set_super_power
    @super_power = SuperPower.find(params[:id])
    authorize @super_power
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def after_update_path_for(resource)
    user_path(resource)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @orders = Order.where(user_id: current_user)
    @super_powers = SuperPower.where(user_id: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperPowerMarket</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="container mt-5 mb-5 pt-3">
    <%= yield %>
    </div>
  </body>
</html>

app/views/orders/_orders.html.erb
  <div class="container">
    <div class="row">
      <% @orders.each do |order| %>
        <div class="col-2  p-1">
          <div class="card" style='height: 180px;'>
            <div class="card-body d-flex flex-column justify-content-between">
                <h5 class='card-title'><%= order.super_power.name %></h5>
                <p class='card-text'><strong>$<%= order.super_power.price %></strong></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/orders/new.html.erb
<div class="container mt-2">
<div class="card text-center">
  <div class="card-header">
    Order
  </div>
  <div class="card-body">
    <h5 class="card-title"><strong><%= @super_power.name %> by <%=@super_power.user.name%></h5></strong>
    <p class="card-text"> <strong>$ <%= @super_power.price %></p></strong>
    <%= simple_form_for [@super_power, @order] do |f| %>
<%= f.submit 'Buy', class: 'btn btn-danger' %>
<% end %>
  </div>
  <div class="card-footer text-muted">
<%= link_to 'Back', super_power_path(@super_power), class: 'text-black' %>
  </div>
</div>
</div>

app/views/orders/shopping.html.erb
  <div class= "container mt-5">

    <div class= "mb-3 text-center">
      <h3>PURCHASES</h3>
    </div>

    <div class="row">
      <% @orders.each do |order| %>
        <div class="col-3  p-1">
          <div class="card my-4" style='height: 100%;'>
            <% if order.super_power.photo.attached? %>
              <div class='card-img-top' style='background-image: url(<%= cl_image_path(power.photo.key) %>)'></div>
              <div class="card-body d-flex flex-column justify-content-between">
                <h5 class='card-title'><%= order.super_power.name %></h5>
                <p class='card-text'><strong>$<%= order.super_power.price.to_s.gsub('.', ',') %>0</strong></p>
                <%= link_to 'View', super_power_path(order.super_power), class: 'btn btn-danger' %>
              </div>
            <% else %>
              <div class="card-img-top" style="background-image: url(https://mrconfeccoes.com.br/wp-content/uploads/2018/03/default.jpg)"></div>
              <div class="card-body d-flex flex-column justify-content-between">
                <h5 class='card-title'><%= order.super_power.name %></h5>
                <p class='card-text'><strong>$<%= order.super_power.price.to_s.gsub('.', ',') %>0</strong></p>
                <%= link_to 'View', super_power_path(order.super_power), class: 'btn btn-danger' %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/orders/show.html.erb
<div class="container mt-2 text-center">
<h3>Compra efetuada com sucesso!</h3>

<p><strong>Número do pedido:</strong> <%= @order.id %></p>

<%= link_to 'Home', super_powers_path, class: 'btn btn-sm btn-danger' %>
</div>

app/views/pages/home.html.erb
 <div class="banner mt-5" style="background-image: url(<%= asset_url "banner-photo.png" %>); background-size: cover; height: 550px;" >
    <div class="container mt-5 d-flex justify-content-center align-items-center h-100">
      <div class="text-banner">
        <h3>Superpower Store</h3>
        <h1>If you're not happy, change it!</h1>
        <%= link_to "Learn More", super_powers_path, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>

  <!-- code a "How it works" section -->
  <div class="container">
    <h2 class="text-center">How it works</h2>
      <div class="card text-center">
      <div class="card-header">
      </div>
      <div class="card-body">
        <h5 class="card-title">Sign-up</h5>
        <p class="card-text">Create your account and get started. </p>
        <%= link_to 'Get started TODAY', new_user_registration_path, class: "card-link", class: 'btn btn-danger' %>
      </div>
      <div class="card-footer text-muted">
      </div>
    </div>
    <div class="card text-center">
      <div class="card-header">
      </div>
      <div class="card-body">
        <h5 class="card-title">Decide if you want to sell, buy or BOTH</h5>
        <p class="card-text">As easy as breathing, you can have a brand new Superpower, or extra cash!</p>
        <%= link_to 'Check out our powers available', super_powers_path, class: "card-link", class: 'btn btn-danger' %>
      </div>
      <div class="card-footer text-muted">
      </div>
    </div>
    <div class="card text-center">
      <div class="card-header">
      </div>
      <div class="card-body">
        <h5 class="card-title">Stress free</h5>
        <p class="card-text">Finally you will be able to be the best version of yourself.</p>
      </div>
      <div class="card-footer text-muted">
      </div>
    </div>
</div>

app/views/reviews/_form.html.erb
<div class="container mt-2">
<h3>Create new comment</h3>
  <%= simple_form_for ([@super_power, @review]) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :rating %>
      <%= f.input :comment %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Create Comment", class: "btn btn-danger" %>
    </div>
  <% end %>
</div>

app/views/reviews/_reviews.html.erb
<body>
  <section id="testimonials">
    <!--heading--->
    <div class="testimonial-heading">
      <span>Comments</span>
    </div>
     <% if @super_power.reviews.empty? %>
                      <small><em class="text-muted"> No comments yet. Be the first one to review this Super Power in the next field</em></small>
                        <% end %>
    <!--testimonials-box-container------>
    <%@super_power.reviews.each do |review|%>
    <div class="testimonial-box-container">
      <!--BOX-1-------------->
      <div class="testimonial-box">
        <!--top------------------------->
        <div class="box-top">
          <!--profile----->
          <div class="profile">
            <!--img---->
            <div class="profile-img">
              <% if review.user.photo.attached? %>
                <%= cl_image_tag review.user.photo.key %>
              <% else %>
              <%= image_tag 'profile.png' %>
              <% end %>
            </div>
            <!--name-and-username-->
            <div class="name-user">
              <strong><%=review.user.name%></strong>
              <span><%=review.user.email%></span>
            </div>
          </div>
          <!--reviews------>
          <div class="reviews"> <% review.rating.times do %>
            <i class="fas fa-star"></i>
         <%end%>
          </div>
        </div>
        <!--Comments---------------------------------------->
        <div class="client-comment">
          <p><%= review.comment%></p>
        </div>
      </div>
    <%end%>
  </section>
</body>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon p-1">
  <div class="container-fluid">
    <%= link_to super_powers_path, class: "navbar-brand" do %>
      <%= image_tag "superhero.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active m-2">
          <%= form_with url: super_powers_path, method: :get, class: 'd-flex' do %>
          <%= text_field_tag :query, params[:query], class: 'form-control mr-sm-2', placeholder: 'Search' %>
          <%= submit_tag 'Search', class: 'btn btn-danger my-2 my-sm-0' %>
          <% end %>
          </li>
          <li class="nav-item dropdown m-2">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Create New Ad", new_super_power_path, class: "dropdown-item" %>
              <%= link_to "My Ads", ads_path, class: "dropdown-item" %>
              <%= link_to "My Shopping", shopping_path, class: "dropdown-item" %>
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
            <% else %>
             <%= image_tag 'profile.png', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Create New Ad", new_super_power_path, class: "dropdown-item" %>
              <%= link_to "My Ads", ads_path, class: "dropdown-item" %>
              <%= link_to "My Shopping", shopping_path, class: "dropdown-item" %>
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= form_with url: root_path, method: :get, class: 'd-flex' do %>
              <%= text_field_tag :query, params[:query], class: 'form-control mr-sm-2', placeholder: 'Search' %>
              <%= submit_tag 'Search', class: 'btn btn-danger my-2 my-sm-0' %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/super_powers/_spower.html.erb
  <div class="container">
    <div class="row">
      <% @super_powers.each do |power| %>
        <div class="col-2  p-1">
          <div class="card" style='height: 180px;'>
            <div class="card-body d-flex flex-column justify-content-between">
                <h5 class='card-title'><%= power.name %></h5>
                <p class='card-text'><strong>$<%= power.price %></strong></p>
                <%= link_to 'Ver Produto', super_power_path(power), class: 'btn btn-danger' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/super_powers/ads.html.erb
<div class="container mt-2 mb-2">
  <div class="row justify-content-between">
    <% @super_powers.each do |power| %>
      <div class="col-3 p-1">
        <div class="card my-4 " style='height: 100%;'>
        <% if power.photo.attached? %>
        <div class='card-img-top' style='background-image: url(<%= cl_image_path(power.photo.key) %>)'></div>
        <div class="card-body d-flex flex-column justify-content-between">
              <h5 class='card-title'><%= power.name %></h5>
              <p class='card-text'><strong>$<%= power.price.to_s.gsub('.', ',') %>0</strong></p>
              <%= link_to 'View', super_power_path(power), class: 'btn btn-danger' %>
          </div>
        <% else %>
        <div class="card-img-top" style="background-image: url(https://mrconfeccoes.com.br/wp-content/uploads/2018/03/default.jpg)"></div>
          <div class="card-body d-flex flex-column justify-content-between">
              <h5 class='card-title'><%= power.name %></h5>
              <p class='card-text'><strong>$<%=  power.price.to_s.gsub('.', ',') %>0</strong></p>
              <%= link_to 'View', super_power_path(power), class: 'btn btn-danger' %>
          </div>
        <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/super_powers/edit.html.erb
<div class="container mt-2">
<h3>Edit your ad</h3>
  <%= simple_form_for @super_power do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :photo, as: :file %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Edit", class: "btn btn-sm btn-danger" %>
    </div>
  <% end %>
</div>

app/views/super_powers/index.html.erb
<div class="container mt-2 mb-2">
  <div class="row">
    <% @super_powers.each do |power| %>
      <div class="col-3  p-1">
        <div class="card my-4" style='height: 100%;'>
        <% if power.photo.attached? %>
        <div class='card-img-top' style='background-image: url(<%= cl_image_path(power.photo.key) %>)'></div>
        <div class="card-body d-flex flex-column justify-content-between">
              <h5 class='card-title'><%= power.name %></h5>
              <p class='card-text'><strong>$ <%= power.price.to_s.gsub('.', ',') %>0</strong></p>
              <%= link_to 'View', super_power_path(power), class: 'btn btn-danger' %>
          </div>
        <% else %>
        <div class="card-img-top" style="background-image: url(https://mrconfeccoes.com.br/wp-content/uploads/2018/03/default.jpg)"></div>
          <div class="card-body d-flex flex-column justify-content-between">
              <h5 class='card-title'><%= power.name %></h5>
              <p class='card-text'><strong>$ <%= power.price.to_s.gsub('.', ',')%>0</strong></p>
              <%= link_to 'View', super_power_path(power), class: 'btn btn-danger' %>
          </div>
        <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/super_powers/new.html.erb
<div class= "container mt-5">
  <div class= "mb-3 text-center">
    <h3>CREATE NEW AD</h3>
  </div>
    <%= simple_form_for @super_power do |f| %>
    <%= f.error_notification %>

    <div class= "form-inputs">
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :photo, as: :file %>
    </div>

    <div class= "form-actions">
      <%= f.button :submit, "Create", class: "btn btn-danger" %>
    </div>
  <% end %>
</div>

app/views/super_powers/show.html.erb
<div class= "container mt-5">
<div class="row">
<div class="col-8 justify-content-center">
  <div class= "titulo mb-3">
    <h1><%= @super_power.name %></h1>
  </div>

  <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">

  <div class="carousel-inner">
    <div class="carousel-item active">
    <% if @super_power.photo.attached? %>
      <%= cl_image_tag @super_power.photo.key, height: 250, width: 250, crop: :fill %>
    <% else %>
    <img src="https://mrconfeccoes.com.br/wp-content/uploads/2018/03/default.jpg" alt="">
    <% end %>
    </div>
</div>
 <p class='mt-2 ml-5'><strong>Sold by: </strong> <%= @super_power.user.name%> </p>
  <div class="card w-50 mt-3">
  <div class="card-body">
    <h5 class="card-title"><strong>Description:</strong></h5>
    <p class="card-text"><%=@super_power.description%></p>
  </div>
</div>

</div>
<div class="card w-50 mt-3">
  <div class="card-body">
    <h5 class="card-title"><strong>To contact the Owner:</strong></h5>
    <p class="card-text"><% @teste = @super_power.user_id%> <p><%= @users.find(@teste).email %></p></p>
  </div>

</div>

<div class="card w-50 mt-3">
  <div class="card-body">
    <h5 class="card-title">Price: $<%= @super_power.price.to_s.gsub('.', ',') %>0</h5>
  </div>
</div>
    <% if current_user %>
      <% if current_user != @super_power.user %>
        <%= link_to 'Buy', new_super_power_order_path(@super_power), class: 'btn  btn-danger m-2',  method: 'post' %>
      <% end %>
      <% if policy(@super_power).edit? %>
        <%= link_to 'Edit', edit_super_power_path(@super_power), class: 'btn  btn-danger m-2' %>
        <%= link_to 'Delete', @super_power, data: {'turbo-method': :delete, 'turbo-confirm': 'Are you sure?'}, class: 'btn  btn-danger m-2' %>
      <% end %>
    <% else %>
      <% session["user_return_to"] = super_power_path(@super_power) %>
      <%= link_to 'Buy', new_user_session_path, class: 'btn  btn-danger m-2'%>
      <%= link_to 'Edit', new_user_session_path, class: 'btn  btn-danger m-2' %>
      <%= link_to 'Delete', new_user_session_path, class: 'btn  btn-danger m-2' %>
    <% end %>
</div>
<div class="col-4 mb-3">
 <%= render "reviews/reviews" %>
 <%= render "reviews/form" %>
 </div>
</div>
 <br>
<section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row">
    <h4> See Another Super Powers:</H4>
    <%@related.each do |f|  %>
      <div class="col-md-12 col-lg-4 mb-4 mb-lg-0">
      <%= link_to super_power_path(f), style:"text-decoration: none; color: black" do  %>
        <div class="card">
          <div class="d-flex justify-content-between">
          </div>
          <% if f.photo.attached? %>
          <div class='card-img-top' style='background-image: url(<%= cl_image_path(f.photo.key) %>)'></div>
          <div class="card-body">
            <div class="d-flex justify-content-between">
            </div>

            <div class="d-flex justify-content-between">
              <h5 class="mb-0"><%= f.name%></h5>
              <h5 class="text-dark mb-0"> $<%= f.price.to_s.gsub('.', ',') %>0</h5>
            </div>

            <div class="d-flex justify-content-between mb-2">
              <div class="ms-auto text-warning">
            </div>
            <% else %>
          <div class="card-img-top" style="background-image: url(https://mrconfeccoes.com.br/wp-content/uploads/2018/03/default.jpg)"></div>
          <div class="card-body">
            <div class="d-flex justify-content-between">
            </div>

            <div class="d-flex justify-content-between">
              <h5 class="mb-0"><%= f.name%></h5>
              <h5 class="text-dark mb-0"> $<%= f.price %></h5>
            </div>

            <div class="d-flex justify-content-between mb-2">
              <div class="ms-auto text-warning">
            </div>
            <% end %>
            </div>
          </div>
        </div>
        <%end%>
      </div>
      <%end%>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<div class="container mt-5">

  <div class="mb-3 text-center">
    <h3>YOUR PROFILE</h3>
  </div>

  <div class="text-center">
    <% if @user.photo.attached? %>
      <div class="p-2">
        <%= cl_image_tag @user.photo.key, height: 200, width: 200, radius: :max,  crop: :fill %>
      </div>
    <% else %>
      <div class="p-2">
        <%= image_tag 'profile.png', height: 200, width: 200, radius: :max,  crop: :fill %>
      </div>
    <% end %>

    <div class="m-3">
      <h4><strong><%= @user.name %></strong></h4>
    </div>

    <h5><strong>Name:</strong> <%= @user.name %></h5>
    <h5><strong>Email:</strong> <%= @user.email%></h5>

    <% session["user_return_to"] = user_path(current_user) %>
    <%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-danger mt-3' %>
  </div>
</div>